
package classup.View;

import classups.Aluno;
import classups.ColecaoAlunos;
import java.awt.Color;
import java.util.List;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.BorderFactory;
import javax.swing.SwingConstants;
import javax.swing.JSeparator;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author n3to
 */
public class Aluno_ClassUP extends javax.swing.JFrame {

    /**
     * Creates new form House_ClassUp
     */
    public Aluno_ClassUP() {
        initComponents();
     
    }
    
    private void carregarAlunosNoPainel() throws SQLException {
        ColecaoAlunos colecao = new ColecaoAlunos();
        List<Aluno> lista = colecao.buscarTodosAlunos();
        
        PainelAlunos.removeAll();
        for (Aluno aluno : lista) {
            JLabel label = new JLabel(aluno.getNome());
            label.setFont(new Font("SansSerif", Font.PLAIN, 14));
            
            label.setBorder(BorderFactory.createEmptyBorder(1, 2, 1, 2));
            label.setPreferredSize(new Dimension(100, 25));
            label.setMaximumSize(new Dimension(Integer.MAX_VALUE, 25));
            
            PainelAlunos.add(label);
            
            // separa a tabela com as linhas 
            JSeparator separar = new JSeparator(SwingConstants.HORIZONTAL);
            separar.setPreferredSize(new Dimension(300, 2));
            separar.setMaximumSize(new Dimension(Integer.MAX_VALUE, 2));
            separar.setForeground(new Color(182, 170, 162));
            
            
            PainelAlunos.add(separar);
            
        }
        PainelAlunos.revalidate();
        PainelAlunos.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jText_Aluno = new javax.swing.JLabel();
        btnAddNota = new javax.swing.JButton();
        btnAddPresenca = new javax.swing.JButton();
        btnAddAluno = new javax.swing.JButton();
        btn_Sinc = new javax.swing.JButton();
        icon_Case1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PainelAlunos = new javax.swing.JPanel();
        jButton_HouseAluno = new javax.swing.JToggleButton();
        jButton_ClassAluno = new javax.swing.JToggleButton();
        jButton_Aluno_Aluno = new javax.swing.JToggleButton();
        jButton_ProfAluno = new javax.swing.JToggleButton();
        icon_Case = new javax.swing.JLabel();
        Image_Fundo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alunos");
        setPreferredSize(new java.awt.Dimension(501, 399));
        setResizable(false);
        getContentPane().setLayout(null);

        jText_Aluno.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jText_Aluno.setForeground(new java.awt.Color(0, 0, 0));
        jText_Aluno.setText("Alunos");
        getContentPane().add(jText_Aluno);
        jText_Aluno.setBounds(50, 10, 120, 30);

        btnAddNota.setBackground(new java.awt.Color(120, 105, 102));
        btnAddNota.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        btnAddNota.setForeground(new java.awt.Color(34, 22, 18));
        btnAddNota.setText("Adicionar nota +");
        btnAddNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNotaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddNota);
        btnAddNota.setBounds(190, 350, 154, 29);

        btnAddPresenca.setBackground(new java.awt.Color(120, 105, 102));
        btnAddPresenca.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        btnAddPresenca.setForeground(new java.awt.Color(34, 22, 18));
        btnAddPresenca.setText("Presença +");
        btnAddPresenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPresencaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddPresenca);
        btnAddPresenca.setBounds(360, 350, 130, 29);

        btnAddAluno.setBackground(new java.awt.Color(120, 105, 102));
        btnAddAluno.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        btnAddAluno.setForeground(new java.awt.Color(34, 22, 18));
        btnAddAluno.setText("Criar Aluno +");
        btnAddAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAluno);
        btnAddAluno.setBounds(50, 350, 130, 29);

        btn_Sinc.setForeground(new java.awt.Color(50, 17, 17));
        btn_Sinc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Update.png"))); // NOI18N
        btn_Sinc.setBorderPainted(false);
        btn_Sinc.setContentAreaFilled(false);
        btn_Sinc.setFocusPainted(false);
        btn_Sinc.setFocusable(false);
        btn_Sinc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Sinc.setMargin(new java.awt.Insets(5, 9, 17, 14));
        btn_Sinc.setRequestFocusEnabled(false);
        btn_Sinc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Sinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SincActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Sinc);
        btn_Sinc.setBounds(430, 10, 65, 40);

        icon_Case1.setBackground(new java.awt.Color(132, 132, 132));
        icon_Case1.setForeground(new java.awt.Color(131, 121, 115));
        icon_Case1.setAutoscrolls(true);
        icon_Case1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 105, 102), 2));
        icon_Case1.setOpaque(true);
        getContentPane().add(icon_Case1);
        icon_Case1.setBounds(430, 10, 60, 40);

        jScrollPane1.setBackground(new java.awt.Color(165, 162, 162));

        PainelAlunos.setBackground(new java.awt.Color(165, 162, 162));
        PainelAlunos.setOpaque(false);
        PainelAlunos.setLayout(new javax.swing.BoxLayout(PainelAlunos, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(PainelAlunos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 52, 440, 290);

        jButton_HouseAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_house.png"))); // NOI18N
        jButton_HouseAluno.setBorderPainted(false);
        jButton_HouseAluno.setContentAreaFilled(false);
        jButton_HouseAluno.setFocusPainted(false);
        jButton_HouseAluno.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_HouseAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HouseAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_HouseAluno);
        jButton_HouseAluno.setBounds(6, 10, 38, 40);

        jButton_ClassAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Class.png"))); // NOI18N
        jButton_ClassAluno.setBorderPainted(false);
        jButton_ClassAluno.setContentAreaFilled(false);
        jButton_ClassAluno.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton_ClassAluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_ClassAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClassAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ClassAluno);
        jButton_ClassAluno.setBounds(0, 60, 46, 30);

        jButton_Aluno_Aluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Aluno (2).png"))); // NOI18N
        jButton_Aluno_Aluno.setSelected(true);
        jButton_Aluno_Aluno.setBorderPainted(false);
        jButton_Aluno_Aluno.setContentAreaFilled(false);
        jButton_Aluno_Aluno.setFocusPainted(false);
        jButton_Aluno_Aluno.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_Aluno_Aluno.setMargin(new java.awt.Insets(8, 21, 20, 14));
        jButton_Aluno_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Aluno_AlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Aluno_Aluno);
        jButton_Aluno_Aluno.setBounds(7, 100, 26, 40);

        jButton_ProfAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Prof.png"))); // NOI18N
        jButton_ProfAluno.setBorderPainted(false);
        jButton_ProfAluno.setContentAreaFilled(false);
        jButton_ProfAluno.setFocusPainted(false);
        jButton_ProfAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProfAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ProfAluno);
        jButton_ProfAluno.setBounds(0, 150, 46, 30);

        icon_Case.setBackground(new java.awt.Color(131, 121, 115));
        icon_Case.setForeground(new java.awt.Color(131, 121, 115));
        icon_Case.setAutoscrolls(true);
        icon_Case.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(131, 121, 115)));
        icon_Case.setOpaque(true);
        getContentPane().add(icon_Case);
        icon_Case.setBounds(70, 80, 50, 30);

        Image_Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/images/Edit_início.png"))); // NOI18N
        getContentPane().add(Image_Fundo);
        Image_Fundo.setBounds(0, 0, 501, 399);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HouseAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HouseAlunoActionPerformed
       House_ClassUp Home = new House_ClassUp();
       Home.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton_HouseAlunoActionPerformed

    private void jButton_Aluno_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Aluno_AlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Aluno_AlunoActionPerformed

    private void jButton_ProfAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProfAlunoActionPerformed
        Professor_ClassUP teacher = new Professor_ClassUP();
        teacher.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_ProfAlunoActionPerformed

    private void btnAddNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNotaActionPerformed
        DialogAddNota addNota = new DialogAddNota(this, rootPaneCheckingEnabled);
        addNota.setVisible(true);
    }//GEN-LAST:event_btnAddNotaActionPerformed

    private void btnAddPresencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPresencaActionPerformed
        DialogAddPresenca addPresenca = new DialogAddPresenca(this, rootPaneCheckingEnabled);
        addPresenca.setLocationRelativeTo(this);
        addPresenca.setVisible(true);
    }//GEN-LAST:event_btnAddPresencaActionPerformed

    private void jButton_ClassAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClassAlunoActionPerformed
        Turma_ClassUP telaTurma = new Turma_ClassUP();
        telaTurma.setLocationRelativeTo(this);
        telaTurma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_ClassAlunoActionPerformed

    private void btnAddAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAlunoActionPerformed
        DialogCriarAluno addAluno = new DialogCriarAluno(this, true);
        addAluno.setLocationRelativeTo(this);
        addAluno.setVisible(true);
    }//GEN-LAST:event_btnAddAlunoActionPerformed

    private void btn_SincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SincActionPerformed
        try {
            carregarAlunosNoPainel();
        } catch (SQLException ex) {
            Logger.getLogger(Aluno_ClassUP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_SincActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aluno_ClassUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aluno_ClassUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aluno_ClassUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aluno_ClassUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aluno_ClassUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image_Fundo;
    private javax.swing.JPanel PainelAlunos;
    private javax.swing.JButton btnAddAluno;
    private javax.swing.JButton btnAddNota;
    private javax.swing.JButton btnAddPresenca;
    private javax.swing.JButton btn_Sinc;
    private javax.swing.JLabel icon_Case;
    private javax.swing.JLabel icon_Case1;
    private javax.swing.JToggleButton jButton_Aluno_Aluno;
    private javax.swing.JToggleButton jButton_ClassAluno;
    private javax.swing.JToggleButton jButton_HouseAluno;
    private javax.swing.JToggleButton jButton_ProfAluno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jText_Aluno;
    // End of variables declaration//GEN-END:variables
}
