/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package classup.View;

import classups.Aluno;
import classups.ColecaoAlunos;
import classup.model.dao.NotaDAO;
import java.awt.Component;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author n3to
 */
public class DialogAddNota extends javax.swing.JDialog {

    /**
     * Creates new form DialogAddNota
     */
    public DialogAddNota(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        rolagemAlunos = new javax.swing.JScrollPane();
        painelNotas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_SalvarNota = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_Sincro = new javax.swing.JButton();
        txtValorNota = new javax.swing.JLabel();
        addPorqueNota = new javax.swing.JTextField();
        txtDescricaoNota = new javax.swing.JLabel();
        addNotaAluno = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Nota");
        setModal(true);
        setPreferredSize(new java.awt.Dimension(395, 320));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(161, 145, 135));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(161, 145, 135), 0), "Alunos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Noto Sans", 1, 13), new java.awt.Color(34, 22, 18))); // NOI18N
        jPanel3.setLayout(null);

        rolagemAlunos.setBackground(new java.awt.Color(161, 145, 135));

        painelNotas.setBackground(new java.awt.Color(161, 145, 135));
        painelNotas.setName("Alunos"); // NOI18N
        painelNotas.setLayout(new javax.swing.BoxLayout(painelNotas, javax.swing.BoxLayout.Y_AXIS));
        rolagemAlunos.setViewportView(painelNotas);

        jPanel3.add(rolagemAlunos);
        rolagemAlunos.setBounds(0, 20, 190, 300);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 190, 320);

        jPanel1.setBackground(new java.awt.Color(130, 121, 115));
        jPanel1.setLayout(null);

        btn_SalvarNota.setBackground(new java.awt.Color(118, 107, 99));
        btn_SalvarNota.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        btn_SalvarNota.setForeground(new java.awt.Color(34, 22, 18));
        btn_SalvarNota.setText("Salvar Nota");
        btn_SalvarNota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 164, 155)));
        btn_SalvarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarNotaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_SalvarNota);
        btn_SalvarNota.setBounds(110, 260, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Update.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(37, 260, 40, 30);

        btn_Sincro.setBackground(new java.awt.Color(118, 107, 99));
        btn_Sincro.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        btn_Sincro.setForeground(new java.awt.Color(34, 22, 18));
        btn_Sincro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 164, 155)));
        btn_Sincro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SincroActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Sincro);
        btn_Sincro.setBounds(10, 260, 90, 30);

        txtValorNota.setForeground(new java.awt.Color(255, 255, 255));
        txtValorNota.setText("Valor da Nota: ");
        jPanel1.add(txtValorNota);
        txtValorNota.setBounds(20, 70, 170, 17);

        addPorqueNota.setBackground(new java.awt.Color(224, 220, 220));
        addPorqueNota.setFont(new java.awt.Font("Noto Sans", 0, 13)); // NOI18N
        addPorqueNota.setForeground(new java.awt.Color(34, 22, 18));
        addPorqueNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPorqueNotaActionPerformed(evt);
            }
        });
        jPanel1.add(addPorqueNota);
        addPorqueNota.setBounds(20, 30, 170, 24);

        txtDescricaoNota.setForeground(new java.awt.Color(255, 255, 255));
        txtDescricaoNota.setText("Descrição da Nota: ");
        jPanel1.add(txtDescricaoNota);
        txtDescricaoNota.setBounds(20, 10, 170, 17);

        addNotaAluno.setBackground(new java.awt.Color(224, 220, 220));
        addNotaAluno.setForeground(new java.awt.Color(34, 22, 18));
        try {
            addNotaAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        addNotaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNotaAlunoActionPerformed(evt);
            }
        });
        jPanel1.add(addNotaAluno);
        addNotaAluno.setBounds(20, 90, 170, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(190, 0, 210, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPorqueNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPorqueNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPorqueNotaActionPerformed

    private void btn_SincroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SincroActionPerformed
        painelNotas.removeAll();
        
        ColecaoAlunos colecao = new ColecaoAlunos();
        List<Aluno> listaAlunos = null;
        try {
            listaAlunos = colecao.buscarTodosAlunos();
        } catch (SQLException ex) {
            Logger.getLogger(DialogAddNota.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (Aluno aluno : listaAlunos) {
            JCheckBox cheBox = new JCheckBox(aluno.getNome());
            
            cheBox.putClientProperty("aluno", aluno);
            
            painelNotas.add(cheBox);
        }
        
        painelNotas.revalidate();
        painelNotas.repaint();
        
    }//GEN-LAST:event_btn_SincroActionPerformed

    private void btn_SalvarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarNotaActionPerformed
        
        Aluno alunoSelecionado = null;

    // Verifica todos os checkboxes para encontrar o que foi selecionado
    for (Component c : painelNotas.getComponents()) {
        if (c instanceof JCheckBox) {
            JCheckBox checkBox = (JCheckBox) c;
            if (checkBox.isSelected()) {
                alunoSelecionado = (Aluno) checkBox.getClientProperty("aluno");
                break; // Pega só o primeiro aluno selecionado
            }
        }
    }

    if (alunoSelecionado == null) {
        JOptionPane.showMessageDialog(this, "Selecione um aluno para adicionar a nota.");
        return;
    }

    String descricao = addPorqueNota.getText().trim();
    String valorTexto = addNotaAluno.getText().trim(); // troca vírgula por ponto

    if (descricao.isEmpty() || valorTexto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha a descrição e o valor da nota.");
        return;
    }

    try {
        double valorNota = Double.parseDouble(valorTexto);

        NotaDAO notaDAO = new NotaDAO();
        notaDAO.salvarNota(descricao, valorNota, alunoSelecionado.getId());

        JOptionPane.showMessageDialog(this, "Nota salva com sucesso!");
        // Limpar campos, se quiser:
        addPorqueNota.setText("");
        addNotaAluno.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Digite um valor de nota válido.");
    }
    }//GEN-LAST:event_btn_SalvarNotaActionPerformed

    private void addNotaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNotaAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNotaAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogAddNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogAddNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogAddNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogAddNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogAddNota dialog = new DialogAddNota(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField addNotaAluno;
    private javax.swing.JTextField addPorqueNota;
    private javax.swing.JButton btn_SalvarNota;
    private javax.swing.JButton btn_Sincro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel painelNotas;
    private javax.swing.JScrollPane rolagemAlunos;
    private javax.swing.JLabel txtDescricaoNota;
    private javax.swing.JLabel txtValorNota;
    // End of variables declaration//GEN-END:variables
}
