/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package classup.View;

/**
 *
 * @author n3to
 */
import classups.Aluno;
import classups.ColecaoAlunos;
import classup.model.dao.NotaDAO;
import classup.model.dao.PresencaDAO;
import java.awt.Component;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

public class DialogAddPresenca extends javax.swing.JDialog {

    /**
     * Creates new form DialogAddNota
     */
    public DialogAddPresenca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
         // Aqui ele pega a data atual!
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        rolagemAlunos = new javax.swing.JScrollPane();
        painelPresenca = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnSalvarNota = new javax.swing.JButton();
        lblDate_Presenca = new javax.swing.JLabel();
        btnPresente = new javax.swing.JRadioButton();
        btnAusente = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btn_Sincronizar = new javax.swing.JButton();

        jRadioButtonMenuItem1.setBackground(new java.awt.Color(224, 220, 220));
        jRadioButtonMenuItem1.setForeground(new java.awt.Color(34, 22, 18));
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Presente");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Presença");
        setModal(true);
        setPreferredSize(new java.awt.Dimension(391, 316));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(161, 145, 135));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(161, 145, 135), 0), "Alunos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Noto Sans", 1, 13), new java.awt.Color(34, 22, 18))); // NOI18N
        jPanel3.setLayout(null);

        rolagemAlunos.setBackground(new java.awt.Color(161, 145, 135));

        painelPresenca.setBackground(new java.awt.Color(161, 145, 135));
        painelPresenca.setName("Alunos"); // NOI18N
        painelPresenca.setLayout(new javax.swing.BoxLayout(painelPresenca, javax.swing.BoxLayout.Y_AXIS));
        rolagemAlunos.setViewportView(painelPresenca);

        jPanel3.add(rolagemAlunos);
        rolagemAlunos.setBounds(0, 20, 190, 300);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 190, 320);

        jPanel1.setBackground(new java.awt.Color(130, 121, 115));
        jPanel1.setLayout(null);

        btnSalvarNota.setBackground(new java.awt.Color(118, 107, 99));
        btnSalvarNota.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        btnSalvarNota.setForeground(new java.awt.Color(34, 22, 18));
        btnSalvarNota.setText("Salvar Presença");
        btnSalvarNota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 164, 155)));
        btnSalvarNota.setFocusable(false);
        btnSalvarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarNotaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvarNota);
        btnSalvarNota.setBounds(40, 270, 130, 30);

        lblDate_Presenca.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        lblDate_Presenca.setForeground(new java.awt.Color(34, 22, 18));
        lblDate_Presenca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblDate_Presenca);
        lblDate_Presenca.setBounds(24, 3, 170, 17);

        buttonGroup1.add(btnPresente);
        btnPresente.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        btnPresente.setForeground(new java.awt.Color(255, 255, 255));
        btnPresente.setText("Ausente");
        btnPresente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresenteActionPerformed(evt);
            }
        });
        jPanel1.add(btnPresente);
        btnPresente.setBounds(50, 140, 130, 30);

        buttonGroup1.add(btnAusente);
        btnAusente.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        btnAusente.setForeground(new java.awt.Color(255, 255, 255));
        btnAusente.setText("Presente");
        jPanel1.add(btnAusente);
        btnAusente.setBounds(50, 100, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Update.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(84, 230, 40, 30);

        btn_Sincronizar.setBackground(new java.awt.Color(118, 107, 99));
        btn_Sincronizar.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        btn_Sincronizar.setForeground(new java.awt.Color(34, 22, 18));
        btn_Sincronizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 164, 155)));
        btn_Sincronizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SincronizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Sincronizar);
        btn_Sincronizar.setBounds(60, 230, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(190, 0, 210, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPresenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPresenteActionPerformed

    private void btn_SincronizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SincronizarActionPerformed
        painelPresenca.removeAll();

        ColecaoAlunos colecao = new ColecaoAlunos();
        List<Aluno> listaAlunos = null;
        try {
            listaAlunos = colecao.buscarTodosAlunos();
        } catch (SQLException ex) {
            Logger.getLogger(DialogAddNota.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Aluno aluno : listaAlunos) {
            JCheckBox cheBox = new JCheckBox(aluno.getNome());

            cheBox.putClientProperty("aluno", aluno);

            painelPresenca.add(cheBox);
        }

        painelPresenca.revalidate();
        painelPresenca.repaint();

    }//GEN-LAST:event_btn_SincronizarActionPerformed

    private void btnSalvarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarNotaActionPerformed
        // Verifica se presente ou ausente está selecionado
    boolean presenteSelecionado = btnAusente.isSelected();
    boolean ausenteSelecionado = btnPresente.isSelected();

    if (!presenteSelecionado && !ausenteSelecionado) {
        JOptionPane.showMessageDialog(this, "Selecione Presente ou Ausente!");
        return;
    }

    // Percorre os checkboxes do painel
    Component[] components = painelPresenca.getComponents();
    boolean alunoSelecionado = false;

    for (Component comp : components) {
        if (comp instanceof JCheckBox checkBox && checkBox.isSelected()) {
            alunoSelecionado = true;
            Aluno aluno = (Aluno) checkBox.getClientProperty("aluno");

            PresencaDAO dao = new PresencaDAO();
            if (presenteSelecionado) {
                dao.registrarPresenca(aluno.getId());
            } else {
                dao.registrarAusencia(aluno.getId());
            }
        }
    }

    if (!alunoSelecionado) {
        JOptionPane.showMessageDialog(this, "Selecione ao menos um aluno.");
        return;
    }

    JOptionPane.showMessageDialog(this, "Presença registrada com sucesso!");
    // Limpa seleção, se quiser
    btnAusente.setSelected(false);
    btnPresente.setSelected(false);
    for (Component comp : components) {
        if (comp instanceof JCheckBox checkBox) {
            checkBox.setSelected(false);
        }
    }
    }//GEN-LAST:event_btnSalvarNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogAddPresenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogAddPresenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogAddPresenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogAddPresenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogAddPresenca dialog = new DialogAddPresenca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAusente;
    private javax.swing.JRadioButton btnPresente;
    private javax.swing.JButton btnSalvarNota;
    private javax.swing.JButton btn_Sincronizar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel lblDate_Presenca;
    private javax.swing.JPanel painelPresenca;
    private javax.swing.JScrollPane rolagemAlunos;
    // End of variables declaration//GEN-END:variables
}
