package classup.View;

    import java.time.LocalDate;
    import java.time.format.TextStyle;
    import java.util.Locale;

public class House_ClassUp extends javax.swing.JFrame {

    /**
     * Creates new form House_ClassUp
     */
    public House_ClassUp() {
        initComponents();
            // Aqui ele pega a data atual!
        LocalDate dataAtual = LocalDate.now();
     
            // Aqui ele formata a data!
        String diaSemana = dataAtual.getDayOfWeek().getDisplayName(TextStyle.FULL, new Locale("pt", "BR"));
        String mes = dataAtual.getMonth().getDisplayName(TextStyle.FULL, new Locale("pt", "BR"));
        String dataFormatada = diaSemana + ", " + dataAtual.getDayOfMonth() + " de " + mes + " > ";
        
            // Agora aqui mostra!
            lblDate.setText(dataFormatada); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_House = new javax.swing.JToggleButton();
        jButton_Class = new javax.swing.JToggleButton();
        jButton_Aluno = new javax.swing.JToggleButton();
        jButton_Prof = new javax.swing.JToggleButton();
        lbl_Hello = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        Image_Fundo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Início");
        setPreferredSize(new java.awt.Dimension(511, 429));
        getContentPane().setLayout(null);

        jButton_House.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_house.png"))); // NOI18N
        jButton_House.setBorderPainted(false);
        jButton_House.setContentAreaFilled(false);
        jButton_House.setFocusPainted(false);
        jButton_House.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_House.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HouseActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_House);
        jButton_House.setBounds(6, 10, 38, 40);

        jButton_Class.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Class.png"))); // NOI18N
        jButton_Class.setBorderPainted(false);
        jButton_Class.setContentAreaFilled(false);
        jButton_Class.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton_Class.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClassActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Class);
        jButton_Class.setBounds(0, 60, 46, 30);

        jButton_Aluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Aluno (2).png"))); // NOI18N
        jButton_Aluno.setSelected(true);
        jButton_Aluno.setBorderPainted(false);
        jButton_Aluno.setContentAreaFilled(false);
        jButton_Aluno.setFocusPainted(false);
        jButton_Aluno.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_Aluno.setMargin(new java.awt.Insets(8, 21, 20, 14));
        jButton_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Aluno);
        jButton_Aluno.setBounds(7, 100, 26, 40);

        jButton_Prof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Prof.png"))); // NOI18N
        jButton_Prof.setBorderPainted(false);
        jButton_Prof.setContentAreaFilled(false);
        jButton_Prof.setFocusPainted(false);
        jButton_Prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProfActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Prof);
        jButton_Prof.setBounds(0, 150, 46, 30);

        lbl_Hello.setBackground(new java.awt.Color(131, 121, 115));
        lbl_Hello.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        lbl_Hello.setForeground(new java.awt.Color(34, 22, 18));
        lbl_Hello.setText("Olá, Bem vindo ao ClassUp");
        getContentPane().add(lbl_Hello);
        lbl_Hello.setBounds(100, 30, 370, 33);

        lblDate.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(34, 22, 18));
        getContentPane().add(lblDate);
        lblDate.setBounds(120, 79, 320, 30);

        Image_Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/images/Edit_início.png"))); // NOI18N
        getContentPane().add(Image_Fundo);
        Image_Fundo.setBounds(0, 0, 501, 399);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_HouseActionPerformed

    private void jButton_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AlunoActionPerformed
        Aluno_ClassUP alunoTela = new Aluno_ClassUP();
        alunoTela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_AlunoActionPerformed

    private void jButton_ProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProfActionPerformed
        Professor_ClassUP telaProfessor = new Professor_ClassUP();
        telaProfessor.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_ProfActionPerformed

    private void jButton_ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClassActionPerformed
        Turma_ClassUP telaTurma = new Turma_ClassUP(); // aqui cria a turma a partir da açao do botão
        telaTurma.setVisible(true); // Entra na tela turma
        dispose(); // fecha a janela de Início
    }//GEN-LAST:event_jButton_ClassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(House_ClassUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(House_ClassUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(House_ClassUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(House_ClassUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new House_ClassUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image_Fundo;
    private javax.swing.JToggleButton jButton_Aluno;
    private javax.swing.JToggleButton jButton_Class;
    private javax.swing.JToggleButton jButton_House;
    private javax.swing.JToggleButton jButton_Prof;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lbl_Hello;
    // End of variables declaration//GEN-END:variables
}
