package classup.View;

import Controller.LoginController;
import classup.model.dao.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author n3to
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        controller = new LoginController(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Visible = new javax.swing.JLabel();
        IconUser = new javax.swing.JLabel();
        Invisible = new javax.swing.JLabel();
        JRegister = new javax.swing.JButton();
        Jentrar = new javax.swing.JButton();
        IconKey = new javax.swing.JLabel();
        JSenha = new javax.swing.JPasswordField();
        jUser = new javax.swing.JTextField();
        Box_square = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login-ClassUP");
        setPreferredSize(new java.awt.Dimension(501, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Visible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/Icon_2°/visivel.png"))); // NOI18N
        getContentPane().add(Visible, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 20, 60));

        IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/user.png"))); // NOI18N
        IconUser.setText("jLabel2");
        getContentPane().add(IconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 180, 260, 110));

        Invisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/Icon_2°/invisivel.png"))); // NOI18N
        Invisible.setText("jLabel2");
        Invisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InvisibleMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                InvisibleMouseReleased(evt);
            }
        });
        getContentPane().add(Invisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 20, 60));

        JRegister.setText("registrar-se");
        JRegister.setBorderPainted(false);
        JRegister.setContentAreaFilled(false);
        JRegister.setFocusPainted(false);
        JRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(JRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 100, 20));

        Jentrar.setBackground(new java.awt.Color(224, 220, 220));
        Jentrar.setForeground(new java.awt.Color(34, 22, 18));
        Jentrar.setText("Entrar");
        Jentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JentrarActionPerformed(evt);
            }
        });
        getContentPane().add(Jentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 80, -1));

        IconKey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/cadeado.png"))); // NOI18N
        getContentPane().add(IconKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 270, 290, 30));

        JSenha.setBackground(new java.awt.Color(224, 220, 220));
        JSenha.setMargin(new java.awt.Insets(2, 16, 2, 6));
        getContentPane().add(JSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 200, 27));

        jUser.setBackground(new java.awt.Color(224, 220, 220));
        jUser.setForeground(new java.awt.Color(34, 22, 18));
        jUser.setMargin(new java.awt.Insets(2, 16, 2, 6));
        jUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserActionPerformed(evt);
            }
        });
        getContentPane().add(jUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 223, 200, 27));

        Box_square.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/Icon_2°/LOGIN(3).png"))); // NOI18N
        getContentPane().add(Box_square, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 280, 400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/images/1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InvisibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvisibleMousePressed
        Visible.setVisible(true);
        Invisible.setVisible(false);
        JSenha.setEchoChar((char)0);
    }//GEN-LAST:event_InvisibleMousePressed

    private void InvisibleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvisibleMouseReleased
    Visible.setVisible(false);
    Invisible.setVisible(true);
    JSenha.setEchoChar('*'); 
    }//GEN-LAST:event_InvisibleMouseReleased

    private void jUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserActionPerformed

    private void JRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRegisterActionPerformed
        controller.abrirTelaCadastro();
    }//GEN-LAST:event_JRegisterActionPerformed

    private void JentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JentrarActionPerformed
        String email = jUser.getText();  // Lê o input do Usuário
        String senha = new String(JSenha.getPassword()); // Lê a senha
        
        UsuarioDAO dao = new UsuarioDAO();
        
        if (dao.autenticar(email, senha)) {
        JOptionPane.showMessageDialog(this, "Sucesso");
        
        // Entra para tela_Principal
        new House_ClassUp().setVisible(true);
        this.dispose();
    } else {
        
        JOptionPane.showMessageDialog(this, "Email ou Senha inválidos!");
        jUser.setText("");
        JSenha.setText("");
            }
    }//GEN-LAST:event_JentrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Box_square;
    private javax.swing.JLabel IconKey;
    private javax.swing.JLabel IconUser;
    private javax.swing.JLabel Invisible;
    private javax.swing.JButton JRegister;
    private javax.swing.JPasswordField JSenha;
    private javax.swing.JButton Jentrar;
    private javax.swing.JLabel Visible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jUser;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }
}
