package classup.View;

/**
 *
 * @author n3to
 */
public class Professor_ClassUP extends javax.swing.JFrame {

    /**
     * Creates new form House_ClassUp
     */
    public Professor_ClassUP() {
        initComponents();
     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jText_Professor = new javax.swing.JLabel();
        jButton_HouseProfessor = new javax.swing.JToggleButton();
        jButton_ClassProfessor = new javax.swing.JToggleButton();
        jButton_Aluno_Professor = new javax.swing.JToggleButton();
        jButton_Prof_Professor = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JLabel();
        informeEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JLabel();
        informeName = new javax.swing.JTextField();
        txtYears = new javax.swing.JLabel();
        informeYears = new javax.swing.JTextField();
        txtSexo = new javax.swing.JLabel();
        informeSexo = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JLabel();
        informeMatricula = new javax.swing.JTextField();
        txtDisciplina = new javax.swing.JLabel();
        infomeDisciplina = new javax.swing.JTextField();
        icon_Case = new javax.swing.JLabel();
        Image_Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Professor");
        setPreferredSize(new java.awt.Dimension(501, 399));
        setResizable(false);
        getContentPane().setLayout(null);

        jText_Professor.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jText_Professor.setForeground(new java.awt.Color(0, 0, 0));
        jText_Professor.setText("Professor");
        getContentPane().add(jText_Professor);
        jText_Professor.setBounds(50, 10, 120, 30);

        jButton_HouseProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_house.png"))); // NOI18N
        jButton_HouseProfessor.setBorderPainted(false);
        jButton_HouseProfessor.setContentAreaFilled(false);
        jButton_HouseProfessor.setFocusPainted(false);
        jButton_HouseProfessor.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_HouseProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HouseProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_HouseProfessor);
        jButton_HouseProfessor.setBounds(6, 10, 38, 40);

        jButton_ClassProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Class.png"))); // NOI18N
        jButton_ClassProfessor.setBorderPainted(false);
        jButton_ClassProfessor.setContentAreaFilled(false);
        jButton_ClassProfessor.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton_ClassProfessor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_ClassProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClassProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ClassProfessor);
        jButton_ClassProfessor.setBounds(0, 60, 46, 30);

        jButton_Aluno_Professor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Aluno (2).png"))); // NOI18N
        jButton_Aluno_Professor.setSelected(true);
        jButton_Aluno_Professor.setBorderPainted(false);
        jButton_Aluno_Professor.setContentAreaFilled(false);
        jButton_Aluno_Professor.setFocusPainted(false);
        jButton_Aluno_Professor.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_Aluno_Professor.setMargin(new java.awt.Insets(8, 21, 20, 14));
        jButton_Aluno_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Aluno_ProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Aluno_Professor);
        jButton_Aluno_Professor.setBounds(7, 100, 26, 40);

        jButton_Prof_Professor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Prof.png"))); // NOI18N
        jButton_Prof_Professor.setBorderPainted(false);
        jButton_Prof_Professor.setContentAreaFilled(false);
        jButton_Prof_Professor.setFocusPainted(false);
        jButton_Prof_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Prof_ProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Prof_Professor);
        jButton_Prof_Professor.setBounds(0, 150, 46, 30);

        jPanel1.setBackground(new java.awt.Color(118, 107, 99));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 170, 162), 2));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        txtEmail.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setText("E-mail:");
        jPanel1.add(txtEmail);
        txtEmail.setBounds(20, 174, 50, 21);

        informeEmail.setBackground(new java.awt.Color(224, 220, 220));
        informeEmail.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        informeEmail.setForeground(new java.awt.Color(34, 22, 18));
        informeEmail.setText("profjapa@gmail.com");
        jPanel1.add(informeEmail);
        informeEmail.setBounds(80, 170, 340, 27);

        txtName.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setText("Nome:");
        jPanel1.add(txtName);
        txtName.setBounds(20, 24, 50, 21);

        informeName.setBackground(new java.awt.Color(224, 220, 220));
        informeName.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        informeName.setForeground(new java.awt.Color(34, 22, 18));
        informeName.setText("Hissamu Wilsson");
        jPanel1.add(informeName);
        informeName.setBounds(80, 20, 340, 27);

        txtYears.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        txtYears.setForeground(new java.awt.Color(255, 255, 255));
        txtYears.setText("Data Nascimento:");
        jPanel1.add(txtYears);
        txtYears.setBounds(20, 54, 130, 21);

        informeYears.setBackground(new java.awt.Color(224, 220, 220));
        informeYears.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        informeYears.setForeground(new java.awt.Color(34, 22, 18));
        informeYears.setText("09/01/1983");
        jPanel1.add(informeYears);
        informeYears.setBounds(150, 50, 270, 27);

        txtSexo.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        txtSexo.setForeground(new java.awt.Color(255, 255, 255));
        txtSexo.setText("Sexo:");
        jPanel1.add(txtSexo);
        txtSexo.setBounds(20, 84, 40, 21);

        informeSexo.setBackground(new java.awt.Color(224, 220, 220));
        informeSexo.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        informeSexo.setForeground(new java.awt.Color(34, 22, 18));
        informeSexo.setText("Masculino");
        jPanel1.add(informeSexo);
        informeSexo.setBounds(70, 80, 350, 27);

        txtMatricula.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        txtMatricula.setForeground(new java.awt.Color(255, 255, 255));
        txtMatricula.setText("Matrícula:");
        jPanel1.add(txtMatricula);
        txtMatricula.setBounds(20, 114, 80, 21);

        informeMatricula.setBackground(new java.awt.Color(224, 220, 220));
        informeMatricula.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        informeMatricula.setForeground(new java.awt.Color(34, 22, 18));
        informeMatricula.setText("40028922");
        jPanel1.add(informeMatricula);
        informeMatricula.setBounds(100, 110, 320, 27);

        txtDisciplina.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        txtDisciplina.setForeground(new java.awt.Color(255, 255, 255));
        txtDisciplina.setText("Disciplina:");
        jPanel1.add(txtDisciplina);
        txtDisciplina.setBounds(20, 144, 80, 21);

        infomeDisciplina.setBackground(new java.awt.Color(224, 220, 220));
        infomeDisciplina.setFont(new java.awt.Font("Noto Sans", 0, 15)); // NOI18N
        infomeDisciplina.setForeground(new java.awt.Color(34, 22, 18));
        infomeDisciplina.setText("computaçao");
        infomeDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infomeDisciplinaActionPerformed(evt);
            }
        });
        jPanel1.add(infomeDisciplina);
        infomeDisciplina.setBounds(100, 140, 320, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 90, 440, 230);

        icon_Case.setBackground(new java.awt.Color(131, 121, 115));
        icon_Case.setForeground(new java.awt.Color(131, 121, 115));
        icon_Case.setAutoscrolls(true);
        icon_Case.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(131, 121, 115)));
        icon_Case.setOpaque(true);
        getContentPane().add(icon_Case);
        icon_Case.setBounds(70, 80, 50, 30);

        Image_Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/images/Edit_início.png"))); // NOI18N
        getContentPane().add(Image_Fundo);
        Image_Fundo.setBounds(0, 0, 501, 399);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HouseProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HouseProfessorActionPerformed
        House_ClassUp home = new House_ClassUp();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_HouseProfessorActionPerformed

    private void jButton_Aluno_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Aluno_ProfessorActionPerformed
        Aluno_ClassUP student = new Aluno_ClassUP();
        student.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_Aluno_ProfessorActionPerformed

    private void jButton_Prof_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Prof_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Prof_ProfessorActionPerformed

    private void jButton_ClassProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClassProfessorActionPerformed
       Turma_ClassUP telaTurma = new Turma_ClassUP();
       telaTurma.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton_ClassProfessorActionPerformed

    private void infomeDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infomeDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infomeDisciplinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Professor_ClassUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Professor_ClassUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Professor_ClassUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Professor_ClassUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Professor_ClassUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image_Fundo;
    private javax.swing.JLabel icon_Case;
    private javax.swing.JTextField infomeDisciplina;
    private javax.swing.JTextField informeEmail;
    private javax.swing.JTextField informeMatricula;
    private javax.swing.JTextField informeName;
    private javax.swing.JTextField informeSexo;
    private javax.swing.JTextField informeYears;
    private javax.swing.JToggleButton jButton_Aluno_Professor;
    private javax.swing.JToggleButton jButton_ClassProfessor;
    private javax.swing.JToggleButton jButton_HouseProfessor;
    private javax.swing.JToggleButton jButton_Prof_Professor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jText_Professor;
    private javax.swing.JLabel txtDisciplina;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtMatricula;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtSexo;
    private javax.swing.JLabel txtYears;
    // End of variables declaration//GEN-END:variables
}
