package classup.View;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import Controller.RegisterController;

/**
 *
 * @author n3to
 */
public class Register extends javax.swing.JFrame {
    private final RegisterController controller;
    
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        controller = new RegisterController(this);
    }

    public JComboBox<String> getComboAcesso() {
        return ComboAcesso;
    }

    public JComboBox<String> getComboSexo() {
        return ComboSexo;
    }

    public JButton getjB_Cadastrar() {
        return jB_Cadastrar;
    }

    public JFormattedTextField getjFormattedTextField1() {
        return jFormattedTextField1;
    }

    public JTextField getjTextDisciplina() {
        return jTextDisciplina;
    }

    public JTextField getjTextEmail() {
        return jTextEmail;
    }

    public JTextField getjTextMatricula() {
        return jTextMatricula;
    }

    public JTextField getjTextName1() {
        return jTextName1;
    }

    public JPasswordField getjTextSenha() {
        return jTextSenha;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterName = new javax.swing.JLabel();
        jTextName1 = new javax.swing.JTextField();
        DateNasc = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jSexo = new javax.swing.JLabel();
        ComboAcesso = new javax.swing.JComboBox<>();
        ComboSexo = new javax.swing.JComboBox<>();
        RegisterMatricula = new javax.swing.JLabel();
        jTextMatricula = new javax.swing.JTextField();
        jText_TipoDeUsuario = new javax.swing.JLabel();
        jB_Cadastrar = new javax.swing.JButton();
        RegisterDisciplina = new javax.swing.JLabel();
        jTextDisciplina = new javax.swing.JTextField();
        RegisterEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        RegisterSenha = new javax.swing.JLabel();
        jTextSenha = new javax.swing.JPasswordField();
        ImageRegister = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(224, 220, 220));
        setMinimumSize(new java.awt.Dimension(501, 590));
        setPreferredSize(new java.awt.Dimension(501, 590));
        getContentPane().setLayout(null);

        RegisterName.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        RegisterName.setForeground(new java.awt.Color(255, 255, 255));
        RegisterName.setText("Nome");
        getContentPane().add(RegisterName);
        RegisterName.setBounds(60, 87, 40, 30);

        jTextName1.setBackground(new java.awt.Color(224, 220, 220));
        jTextName1.setForeground(new java.awt.Color(34, 22, 18));
        jTextName1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextName1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        getContentPane().add(jTextName1);
        jTextName1.setBounds(60, 115, 190, 30);

        DateNasc.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        DateNasc.setForeground(new java.awt.Color(255, 255, 255));
        DateNasc.setText("Data de Nascimento");
        getContentPane().add(DateNasc);
        DateNasc.setBounds(60, 150, 136, 20);

        jFormattedTextField1.setBackground(new java.awt.Color(224, 220, 220));
        jFormattedTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jFormattedTextField1.setForeground(new java.awt.Color(34, 22, 18));
        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setSelectedTextColor(new java.awt.Color(224, 220, 220));
        jFormattedTextField1.setSelectionColor(new java.awt.Color(224, 220, 220));
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(60, 170, 190, 30);

        jSexo.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jSexo.setForeground(new java.awt.Color(255, 255, 255));
        jSexo.setText("Sexo");
        getContentPane().add(jSexo);
        jSexo.setBounds(60, 200, 31, 30);

        ComboAcesso.setBackground(new java.awt.Color(224, 220, 220));
        ComboAcesso.setForeground(new java.awt.Color(34, 22, 18));
        ComboAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Professor", "Administrador" }));
        ComboAcesso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 220, 220), 0));
        getContentPane().add(ComboAcesso);
        ComboAcesso.setBounds(262, 113, 190, 33);

        ComboSexo.setBackground(new java.awt.Color(224, 220, 220));
        ComboSexo.setForeground(new java.awt.Color(34, 22, 18));
        ComboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Masculino", "Feminino" }));
        ComboSexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 220, 220), 0));
        getContentPane().add(ComboSexo);
        ComboSexo.setBounds(60, 226, 190, 33);

        RegisterMatricula.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        RegisterMatricula.setForeground(new java.awt.Color(255, 255, 255));
        RegisterMatricula.setText("Matrícula");
        getContentPane().add(RegisterMatricula);
        RegisterMatricula.setBounds(60, 266, 75, 14);

        jTextMatricula.setBackground(new java.awt.Color(224, 220, 220));
        jTextMatricula.setForeground(new java.awt.Color(34, 22, 18));
        jTextMatricula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextMatricula.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        getContentPane().add(jTextMatricula);
        jTextMatricula.setBounds(60, 283, 190, 30);

        jText_TipoDeUsuario.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jText_TipoDeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jText_TipoDeUsuario.setText("Tipo de Usuário");
        getContentPane().add(jText_TipoDeUsuario);
        jText_TipoDeUsuario.setBounds(260, 91, 120, 22);

        jB_Cadastrar.setContentAreaFilled(false);
        jB_Cadastrar.setDefaultCapable(false);
        jB_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jB_Cadastrar);
        jB_Cadastrar.setBounds(160, 330, 190, 40);

        RegisterDisciplina.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        RegisterDisciplina.setForeground(new java.awt.Color(255, 255, 255));
        RegisterDisciplina.setText("Disciplina");
        getContentPane().add(RegisterDisciplina);
        RegisterDisciplina.setBounds(261, 150, 80, 20);

        jTextDisciplina.setBackground(new java.awt.Color(224, 220, 220));
        jTextDisciplina.setForeground(new java.awt.Color(34, 22, 18));
        jTextDisciplina.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextDisciplina.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        getContentPane().add(jTextDisciplina);
        jTextDisciplina.setBounds(262, 171, 189, 30);

        RegisterEmail.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        RegisterEmail.setForeground(new java.awt.Color(255, 255, 255));
        RegisterEmail.setText("Email");
        getContentPane().add(RegisterEmail);
        RegisterEmail.setBounds(260, 207, 37, 20);

        jTextEmail.setBackground(new java.awt.Color(224, 220, 220));
        jTextEmail.setForeground(new java.awt.Color(34, 22, 18));
        jTextEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        getContentPane().add(jTextEmail);
        jTextEmail.setBounds(262, 228, 190, 30);

        RegisterSenha.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        RegisterSenha.setForeground(new java.awt.Color(255, 255, 255));
        RegisterSenha.setText("Senha");
        getContentPane().add(RegisterSenha);
        RegisterSenha.setBounds(260, 264, 51, 20);

        jTextSenha.setBackground(new java.awt.Color(224, 220, 220));
        jTextSenha.setForeground(new java.awt.Color(34, 22, 18));
        jTextSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jTextSenha.setSelectedTextColor(new java.awt.Color(34, 22, 18));
        jTextSenha.setSelectionColor(new java.awt.Color(224, 220, 220));
        jTextSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextSenha);
        jTextSenha.setBounds(261, 284, 190, 30);

        ImageRegister.setIcon(new javax.swing.ImageIcon("/home/n3to/NetBeansProjects/ClassUp/src/classup/View/images/register.png")); // NOI18N
        getContentPane().add(ImageRegister);
        ImageRegister.setBounds(0, 0, 500, 399);

        jPanel1.setBackground(new java.awt.Color(224, 220, 220));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSenhaActionPerformed

    private void jB_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_CadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboAcesso;
    private javax.swing.JComboBox<String> ComboSexo;
    private javax.swing.JLabel DateNasc;
    private javax.swing.JLabel ImageRegister;
    private javax.swing.JLabel RegisterDisciplina;
    private javax.swing.JLabel RegisterEmail;
    private javax.swing.JLabel RegisterMatricula;
    private javax.swing.JLabel RegisterName;
    private javax.swing.JLabel RegisterSenha;
    private javax.swing.JButton jB_Cadastrar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jSexo;
    private javax.swing.JTextField jTextDisciplina;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextMatricula;
    private javax.swing.JTextField jTextName1;
    private javax.swing.JPasswordField jTextSenha;
    private javax.swing.JLabel jText_TipoDeUsuario;
    // End of variables declaration//GEN-END:variables
}
