
package classup.View;

import classups.Aluno;
import classups.ColecaoAlunos;
import classups.ColecaoNotas;
import classup.model.dao.NotaDAO;
import classup.model.dao.PresencaDAO;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JSeparator;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;

/**
 *
 * @author n3to
 */
public class Turma_ClassUP extends javax.swing.JFrame {

    /**
     * Creates new form House_ClassUp
     */
    public Turma_ClassUP() {
        initComponents();
     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jText_Turma = new javax.swing.JLabel();
        jBut_Sincronizar = new javax.swing.JButton();
        icon_Square2 = new javax.swing.JLabel();
        jButton_HouseTurma = new javax.swing.JToggleButton();
        jButton_ClassTurma = new javax.swing.JToggleButton();
        jButton_AlunoTurma = new javax.swing.JToggleButton();
        jButton_ProfTurma = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PainelDescricao = new javax.swing.JPanel();
        icon_Case = new javax.swing.JLabel();
        Image_Fundo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatório dos Alunos");
        setPreferredSize(new java.awt.Dimension(501, 399));
        setResizable(false);
        getContentPane().setLayout(null);

        jText_Turma.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jText_Turma.setForeground(new java.awt.Color(0, 0, 0));
        jText_Turma.setText("Relátorio Alunos");
        getContentPane().add(jText_Turma);
        jText_Turma.setBounds(50, 10, 220, 30);

        jBut_Sincronizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Update.png"))); // NOI18N
        jBut_Sincronizar.setBorderPainted(false);
        jBut_Sincronizar.setContentAreaFilled(false);
        jBut_Sincronizar.setFocusPainted(false);
        jBut_Sincronizar.setFocusable(false);
        jBut_Sincronizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBut_Sincronizar.setMargin(new java.awt.Insets(5, 9, 17, 14));
        jBut_Sincronizar.setRequestFocusEnabled(false);
        jBut_Sincronizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBut_Sincronizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_SincronizarActionPerformed(evt);
            }
        });
        getContentPane().add(jBut_Sincronizar);
        jBut_Sincronizar.setBounds(350, 10, 130, 50);

        icon_Square2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/-2°fundTP.png"))); // NOI18N
        getContentPane().add(icon_Square2);
        icon_Square2.setBounds(350, 10, 130, 50);

        jButton_HouseTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_house.png"))); // NOI18N
        jButton_HouseTurma.setBorderPainted(false);
        jButton_HouseTurma.setContentAreaFilled(false);
        jButton_HouseTurma.setFocusPainted(false);
        jButton_HouseTurma.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton_HouseTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HouseTurmaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_HouseTurma);
        jButton_HouseTurma.setBounds(6, 10, 38, 40);

        jButton_ClassTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Class.png"))); // NOI18N
        jButton_ClassTurma.setBorderPainted(false);
        jButton_ClassTurma.setContentAreaFilled(false);
        jButton_ClassTurma.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton_ClassTurma.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jButton_ClassTurma);
        jButton_ClassTurma.setBounds(0, 60, 46, 30);

        jButton_AlunoTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Aluno (2).png"))); // NOI18N
        jButton_AlunoTurma.setSelected(true);
        jButton_AlunoTurma.setBorderPainted(false);
        jButton_AlunoTurma.setContentAreaFilled(false);
        jButton_AlunoTurma.setFocusPainted(false);
        jButton_AlunoTurma.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_AlunoTurma.setMargin(new java.awt.Insets(8, 21, 20, 14));
        jButton_AlunoTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AlunoTurmaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_AlunoTurma);
        jButton_AlunoTurma.setBounds(7, 100, 26, 40);

        jButton_ProfTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/icons/IconsFrame/Button_Prof.png"))); // NOI18N
        jButton_ProfTurma.setBorderPainted(false);
        jButton_ProfTurma.setContentAreaFilled(false);
        jButton_ProfTurma.setFocusPainted(false);
        jButton_ProfTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProfTurmaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ProfTurma);
        jButton_ProfTurma.setBounds(0, 150, 46, 30);

        jScrollPane1.setBackground(new java.awt.Color(165, 162, 162));

        PainelDescricao.setBackground(new java.awt.Color(165, 162, 162));
        PainelDescricao.setOpaque(false);
        PainelDescricao.setLayout(new javax.swing.BoxLayout(PainelDescricao, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(PainelDescricao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 80, 440, 290);

        icon_Case.setBackground(new java.awt.Color(131, 121, 115));
        icon_Case.setForeground(new java.awt.Color(131, 121, 115));
        icon_Case.setAutoscrolls(true);
        icon_Case.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(131, 121, 115)));
        icon_Case.setOpaque(true);
        getContentPane().add(icon_Case);
        icon_Case.setBounds(70, 80, 50, 30);

        Image_Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classup/View/images/Edit_início.png"))); // NOI18N
        getContentPane().add(Image_Fundo);
        Image_Fundo.setBounds(0, 0, 501, 399);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HouseTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HouseTurmaActionPerformed
        // TODO add your handling code here:
        House_ClassUp home = new House_ClassUp();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_HouseTurmaActionPerformed

    private void jButton_AlunoTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AlunoTurmaActionPerformed
        Aluno_ClassUP telaAluno = new Aluno_ClassUP();
        telaAluno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_AlunoTurmaActionPerformed

    private void jButton_ProfTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProfTurmaActionPerformed
        Professor_ClassUP telaProf = new Professor_ClassUP();
        telaProf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_ProfTurmaActionPerformed

    private void jBut_SincronizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_SincronizarActionPerformed
        PainelDescricao.removeAll(); // Limpa o painel

    ColecaoAlunos colecao = new ColecaoAlunos();
    List<Aluno> lista = null;
        try {
            lista = colecao.buscarTodosAlunos();
        } catch (SQLException ex) {
            Logger.getLogger(Turma_ClassUP.class.getName()).log(Level.SEVERE, null, ex);
        }

    NotaDAO notaDAO = new NotaDAO();
    PresencaDAO presencaDAO = new PresencaDAO();

    for (Aluno aluno : lista) {
        String nome = aluno.getNome();
        int id = aluno.getId();

        // Busca nota
        ColecaoNotas nota = notaDAO.buscarNotaPorAlunoId(id); // Crie esse método
        String descNota = (nota != null) ? nota.getDescricao() : "Sem nota";
        double valorNota = (nota != null) ? nota.getValorNotas() : 0.0;

        // Busca presenças e ausências
        int totalPresencas = presencaDAO.contarPresencasPorAluno(id);
        int totalAusencias = presencaDAO.contarAusenciasPorAluno(id);

        // Criação do texto do relatório
        StringBuilder relatorio = new StringBuilder();
        relatorio.append("Nome: ").append(nome).append("\n");
        relatorio.append("Nota: ").append(valorNota).append("\n");
        relatorio.append("Descrição da Nota: ").append(descNota).append("\n");
        relatorio.append("Presenças: ").append(totalPresencas).append("\n");
        relatorio.append("Ausências: ").append(totalAusencias);

        JTextArea area = new JTextArea(relatorio.toString());
        area.setEditable(false);
        area.setFont(new Font("SansSerif", Font.PLAIN, 13));
        area.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        area.setBackground(new Color(245, 245, 245));

        PainelDescricao.add(area);

        // Separador
        JSeparator separador = new JSeparator(SwingConstants.HORIZONTAL);
        separador.setForeground(new Color(180, 180, 180));
        PainelDescricao.add(separador);
    }

    PainelDescricao.revalidate();
    PainelDescricao.repaint();
    }//GEN-LAST:event_jBut_SincronizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Turma_ClassUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Turma_ClassUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Turma_ClassUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Turma_ClassUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Turma_ClassUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image_Fundo;
    private javax.swing.JPanel PainelDescricao;
    private javax.swing.JLabel icon_Case;
    private javax.swing.JLabel icon_Square2;
    private javax.swing.JButton jBut_Sincronizar;
    private javax.swing.JToggleButton jButton_AlunoTurma;
    private javax.swing.JToggleButton jButton_ClassTurma;
    private javax.swing.JToggleButton jButton_HouseTurma;
    private javax.swing.JToggleButton jButton_ProfTurma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jText_Turma;
    // End of variables declaration//GEN-END:variables
}
